### ISSUE TITLE
how to download flac in genie?

### ISSUE THREAD

**Issue by wlvlvlw** [Slyyxp/rsack#27]
I'm already using the flac subscription. but download is only 320kbps.
how to download flac? Is there another command?
And what does "thread" mean?

thank u sir.

**Comment by Slyyxp** [comment]
I have confirmed that Genie is currently functioning and able to download 24bit.
Perhaps the album you are trying to download is only available in 320kbps.
To be sure of this post the command you are using here and I will run it on my end.

'Threads' is the number of concurrent downloads.

**Comment by wlvlvlw** [comment]
Then, does it automatically set the quality and download it?
---
I tested 24bit download good well. 
Just like you said that i tried to only available 320kbps album.
I hope there is also a sound quality option.

really thank you sir.

**Comment by Slyyxp** [comment]
> ## Then, does it automatically set the quality and download it?

The answer is yes.
Genie and Bugs currently automatically download the maximum possible quality.
I plan on adding support for quality selection, but this cannot force FLAC for releases only available in MP3.
