### ISSUE TITLE
Artist folder configuration.

### ISSUE THREAD

**Issue by JourneyHua** [Slyyxp/rsack#29]
Somebody as me, don't need artist_folders, maybe consider set a config like BugsPy to close?

**Comment by Slyyxp** [comment]
Can be done.

**Comment by Slyyxp** [comment]
8a2081a3f1ad7875adb194be77fe40655a12001b

**Comment by Slyyxp** [comment]
Configuration will need to be recreated to include the 'artist_folders' field.
