### ISSUE TITLE
requests.exceptions.HTTPError: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by Slyyxp** [Slyyxp/rsack#3]
Unavailable tracks are not skipped.

**Comment by sagarsadhu** [comment]
Hi, I am interested to work on this. Could you please send PR ?

**Comment by Slyyxp** [comment]
Caught with https://github.com/Slyyxp/rsack/commit/80fc116d30d0d09a8b1e96608aa210294236b6a1
