### ISSUE TITLE
Skips downloading songs with characters ?, :, 

### ISSUE THREAD

**Issue by sansalayne** [Slyyxp/rsack#31]
Hi, I noticed that the script skips downloading songs that contain ?, : in their filename.

For example, when downloading this album https://music.bugs.co.kr/album/4041263?wl_ref=list_ab_03_ar, it appears like this:

> C:\Users\x>rsack -b -u https://music.bugs.co.kr/album/4041263?wl_ref=li
> st_ab_03_ar
> 2022-04-04 12:37:15.233 | INFO     | rsack.clients.bugs:auth:26 - Login Successf
> ul
> 2022-04-04 12:37:16.104 | INFO     | rsack.bugs:_album:53 - Album: ? ??? ??? ??
> ???? (???? ??? X ?? (JOY))
> 2022-04-04 12:37:16.111 | DEBUG    | rsack.bugs:_album:67 - Creating C:\Users\x
>\download\?? (JOY) - ? ??? ??? ?? ???_ (???? ??? X ?? (JOY))
> 2022-04-04 12:37:17.345 | INFO     | rsack.bugs:_download_cover:130 - Cover artw
> ork downloaded.
> 2022-04-04 12:37:17.358 | INFO     | rsack.bugs:_album:76 - Threads: 1
> 2022-04-04 12:37:17.444 | DEBUG    | rsack.bugs:_download:87 - Processing: 61041
> 67
> 2022-04-04 12:37:18.733 | DEBUG    | rsack.bugs:_download:87 - Processing: 61041
> 68
> 
> C:\Users\x>

~~Sorry for my English~~

**Comment by Slyyxp** [comment]
Fixed with latest commit.

https://github.com/Slyyxp/rsack/commit/c81c862f297624519c7882f5e4ba89de1d568f44
