### ISSUE TITLE
Label (id3.TPUB) not supported.

### ISSUE THREAD

**Issue by steamgirl2020** [Slyyxp/rsack#33]
The bug's metadata does not support label tags, showing blank，but BugsPy-master support

**Comment by Slyyxp** [comment]
```
    meta = {
        "ALBUM": track['album_title'],
        "ALBUMARTIST": track['artist_disp_nm'],
        "ARTIST": track['artist_disp_nm'],
        "TITLE": track['track_title'],
        "DISCNUMBER": str(track['disc_id']),
        "DISCTOTAL": str(album['disc_total']),
        "TRACKNUMBER": str(track['track_no']),
        "TRACKTOTAL": str(track['track_total']),
        "COMMENT": str(track['track_id']),
        "DATE": _format_date(track['release_ymd']),
        "GENRE": album['genre_str'],
        "LABEL": "",
        "LYRICS": lyrics
    }
    ```

Label was left blank here.
I can't recall whether was a reason or not I left it blank or whether I just overlooked.

Will look into it.

**Comment by Slyyxp** [comment]
I have put forward a fix based on my previous code. It is available temporarily on a new branch until it has been confirmed to be fixed. https://github.com/Slyyxp/rsack/tree/Slyyxp-Patch-1

I do not have an account to test with so I would appreciate if someone can indicate to me whether this works as intended.

**Comment by Slyyxp** [comment]
I'll take your word for it.
I won't be paying for another Bugs account in near future so I can't fix this for now.

Someone else can take a look at the meta and see what needs to be appended if they want.

**Comment by Slyyxp** [comment]
Got my hands on an account so was able to fix this.
Labels are now properly added to both FLAC and MP3

e0f873bc4f990cb2ca141bc26a6daf96d406a837
