### ISSUE TITLE
No regex match for urls leading with "www."

### ISSUE THREAD

**Issue by ilysnemo** [Slyyxp/rsack#34]
![image](https://user-images.githubusercontent.com/58479574/174523739-339e8a5d-30c6-4836-994f-c49db9e30f81.png)
Getting this error, the url is correct right?

**Comment by Slyyxp** [comment]
The url is correct, will look into this right now and get back.

**Comment by Slyyxp** [comment]
This is caused by the leading "www."

**Comment by Slyyxp** [comment]
Fixed with
76be315be67666ca30a1479d9f28350ff12441f6

**Comment by ilysnemo** [comment]
![image](https://user-images.githubusercontent.com/58479574/174529101-117d722b-70d2-400c-b5d2-bb998a27701b.png)
Still invalid url

**Comment by Slyyxp** [comment]
I'm not sure why this doesn't match since my regex is poor.
I put a bandaid on it for now since I need to sleep. If someone can fix my regex that'd be great.
c885b52820bfe8cfd13456ed9b909b13782e2e30

In the meantime it should work with both url variants.

**Comment by ilysnemo** [comment]
Ok i hope someone will fix it. Thanks sly, sleep well. Sorry for bothering you this night lol

**Comment by Slyyxp** [comment]
Technically it's fixed, just not in an appropriate manner.

**Comment by ilysnemo** [comment]
It still error:(
Can i have your contact? like discord or something else. It would be nice reporting the error personally, if you don;t mid

**Comment by Slyyxp** [comment]
My Discord is **Slyy#3040**.

**Comment by Slyyxp** [comment]
Closing this since it now functions as intended.
