### ISSUE TITLE
Cover Size Option

### ISSUE THREAD

**Issue by Yuq-q** [Slyyxp/rsack#59]
Hello, thank you for maintaining this project. I noticed that in your previous project [link](https://github.com/Slyyxp/BugsPy#:~:text=cover_size,to%20download%20%2B%20embed).  It can choose the pixel size of the cover when downloading. If possible, can this option be added to this project as well？Thank you

**Comment by Slyyxp** [comment]
This can be done without much issue for Bugs.
Genie also provides multiple cover artwork options in their API response if i remember correctly so that should also be fine.

**Comment by Slyyxp** [comment]
Done for Bugs.
Won't be done for Genie as it looks like all they're storing is 600x600 and original.

Check wiki for new configuration.
https://github.com/Slyyxp/rsack/wiki/Configuration

**Comment by Yuq-q** [comment]
> _Edit:_ I should add that I **DO NOT** recommend using the original album artwork as they're usually 3000x3000. These images will be embedded into your music files bloating them considerably.

I see, thanks for your reminder
