### ISSUE TITLE
auth error using termux

### ISSUE THREAD

**Issue by aespapa** [Slyyxp/rsack#71]
using termux with bugs.co.kr that auth error. 
genie is fine. 
how to solve this problem in termux?

CRITICAL | rsack.clients.bugs:auth:27 - Authentication Error, Invalid Credentials
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/rsack", line 33, in <module>
    sys.exit(load_entry_point('rsack==0.6.8', 'console_scripts', 'rsack')())
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/rsack-0.6.8-py3.10.egg/rsack/main.py", line 31, in main
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/rsack-0.6.8-py3.10.egg/rsack/bugs.py", line 24, in init
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/rsack-0.6.8-py3.10.egg/rsack/clients/bugs.py", line 30, in auth
TypeError: 'NoneType' object is not subscriptable

**Comment by Slyyxp** [comment]
As the message suggests, first thing you should do is check the credentials ARE actually valid.

Also double check the formatting of `rsack_settings.ini` making sure that you have not made any typo's in:
1. The keys (eg. the word username)
2. '=' present between keys and values.

I do not personally run scripts off of Android devices and I am not entirely familiar with the file structure. Should work fine though.
My guess is you have an invalid configuration file.

**Comment by aespapa** [comment]
> As the message suggests, first thing you should do is check the credentials ARE actually valid.
> 
> Also double check the formatting of `rsack_settings.ini` making sure that you have not made any typo's in:
> 
> 1. The keys (eg. the word username)
> 2. '=' present between keys and values.
> 
> I do not personally run scripts off of Android devices and I am not entirely familiar with the file structure. Should work fine though. My guess is you have an invalid configuration file.

you're right. I’ll give you that. thank you
