### ISSUE TITLE
Appending date to album's folder name like BugsPy

### ISSUE THREAD

**Issue by snowbie** [Slyyxp/rsack#73]
I've just renewed my Bugs subscripiton after a long period and did some tests with this (thanks for maintaining this by the way!), and I've noticed publication dates are no longer appended to the folder name..
For example, the original BugsPy
````
015B
-----015B - Second Episode [1991.05.01]
-----015B - The Fourth Movement [1993.09.01]
````
With rsack
````
015B
-----015B - Second Episode
-----015B - The Fourth Movement
````
It's a pretty small thing, but since each folder is named differently, updating my collection will duplicate my entire library. 
A BugsPy compatible naming setting would be nice. If not a setting, can you tell me what needs to be added to fix this? I skimmed through the code and couldn't find the line that addresses this, though I'm not very good at Python.

**Comment by Slyyxp** [comment]
Re-Install from source:

```bash
$ pip uninstall rsack
$ git clone https://github.com/Slyyxp/rsack.git
$ cd rsack
$ python setup.py install
```

Refer to the configuration example for appending date:
https://github.com/Slyyxp/rsack/blob/master/rsack_settings.ini.example

_0.725 will not be uploaded to pip, I am not happy with the current configuration setup._
