### ISSUE TITLE
no module named "cryptodome" 

### ISSUE THREAD

**Issue by countthesaints** [Slyyxp/rsack#81]
I recently ran pip3 install --upgrade rsack as I noticed there were changes here and now get this error any time I try to download something from Bugs

> Tessellate:~ kenji$ rsack -u https://music.bugs.co.kr/album/4083156
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.11/bin/rsack", line 5, in <module>
>     from rsack.main import main
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/rsack/main.py", line 6, in <module>
>     from rsack import bugs, genie, kkbox
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/rsack/kkbox.py", line 7, in <module>
>     from rsack.clients.kkbox import KkboxAPI
>   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/rsack/clients/kkbox.py", line 6, in <module>
>     from Cryptodome.Cipher import ARC4
> ModuleNotFoundError: No module named 'Cryptodome'

I'm not quite sure what's happened as I downloaded music fine last week.

**Comment by Slyyxp** [comment]
https://pycryptodome.readthedocs.io/en/latest/src/installation.html

```sh
$ pip install pycryptodome
```

**Comment by Slyyxp** [comment]
Now included in setup.py https://github.com/Slyyxp/rsack/commit/a9d2502d710a75c56f687378a9bfdeb96b453d54

**Comment by countthesaints** [comment]
should note that it required 
> $ pip install pycryptodome**x**

and not
> $ pip install pycryptodome
