### ISSUE TITLE
GUI release plans?

### ISSUE THREAD

**Issue by ILIKECHICKENTOOMUCH** [Slyyxp/rsack#89]
Hello,
There's an album I really want to get from Bugs, and then I saw this site, and I got excited.
But I want to try it, but I have no understanding of the command.
I want a GUI version, is it impossible?

**Comment by Slyyxp** [comment]
There will be no GUI.

**Comment by ILIKECHICKENTOOMUCH** [comment]
@Slyyxp 
Thank you for the reply.  감사합니다. :)
I'm so sorry, but can I ask you about how to use it?

https://git-scm.com/download/win
I got the program. I even installed it with the <git clone https://github.com/Slyyxp/rsack.git> command, 
But I'm not sure how to proceed after that.
I've been searching YouTube hard, but I can't find an example of a situation like mine.

**Comment by Slyyxp** [comment]
Install Python and follow the installation guide.
https://github.com/Slyyxp/rsack#readme
https://github.com/Slyyxp/rsack/blob/master/README.en.md


Usage example: `rsack -u https://music.bugs.co.kr/album/4088247`
