### ISSUE TITLE
[help] How to change password

### ISSUE THREAD

**Issue by skylover007** [Slyyxp/rsack#9]
Thank you very much for sharing.
I made a mistake when I first inputed the password, how do I need to modify it, I can't find the path of Settings.ini

![image](https://user-images.githubusercontent.com/35911123/152900014-9ba95fad-d8f6-4ded-a77b-0e959d15535f.png)

**Comment by Slyyxp** [comment]
`Settings.ini` is located in your home folder. `C:\Users\?\Settings.ini`

You can re-create the file by passing `-cfg, --config`
For example: `rsack -cfg`

**Comment by skylover007** [comment]
> `rsack_settings.ini` is located in your home folder. `C:\Users\?\rsack_settings.ini`
> 
> You can re-create the file by passing `-cfg, --config` For example: `rsack -cfg`

Thank you
